/* ---------- 10 languages: device language first, then device region ---------- */
Object.assign(LANGS,{
  hi:{name:"हिन्दी",en:"Hindi",dir:"ltr",tts:"hi-IN"},bn:{name:"বাংলা",en:"Bengali",dir:"ltr",tts:"bn-BD"},id:{name:"Bahasa Indonesia",en:"Indonesian",dir:"ltr",tts:"id-ID"},
  zh:{name:"中文",en:"Chinese",dir:"ltr",tts:"zh-CN"},es:{name:"Español",en:"Spanish",dir:"ltr",tts:"es-ES"},fr:{name:"Français",en:"French",dir:"ltr",tts:"fr-FR"}
});
LANGS.ar.en="Arabic"; LANGS.en.en="English"; LANGS.ur.en="Urdu"; LANGS.tl.en="Filipino";
const LANG_ORDER=["ar","en","ur","hi","bn","tl","id","zh","es","fr"];
T.hi={tab_scan:"जाँचें",tab_sim:"संदेश",tab_call:"कॉल",tab_train:"अभ्यास",tab_more:"और",sub_scan:"धोखाधड़ी के खिलाफ आपकी स्मार्ट ढाल",
  h_scan:"किसी भी संदेश को<br>क्लिक करने से पहले जाँचें",sub_scan2:"SMS, WhatsApp या ईमेल",lbl_msg:"आपको मिला संदेश",ph_msg:"संदेश यहाँ पेस्ट करें…",btn_scan:"संदेश जाँचें",btn_qr:"QR स्कैन",
  safe_t:"सुरक्षित लगता है",safe_s:"कोई स्पष्ट खतरा नहीं। फिर भी अपना कोड किसी को न दें।",suspicious_t:"संदिग्ध",suspicious_s:"सावधान रहें। पक्का होने तक किसी लिंक पर क्लिक न करें।",danger_t:"खतरा",danger_s:"लिंक न खोलें, जवाब न दें और कोई कोड न दें।",
  word_safe:"सुरक्षित है",word_suspicious:"संदिग्ध है",word_danger:"खतरनाक है",v_example:"उदाहरण · कोई उदाहरण चुनें या अपना संदेश पेस्ट करें",v_quick:"आपके फ़ोन पर तुरंत जाँच",v_two:"दो स्तर की जाँच के बाद",
  sec_msg:"आपका संदेश, और फ़तिन ने क्या पकड़ा",lg1:"खतरा",lg2:"नकली नाम",lg3:"सुरक्षा संकेत",sec_dis:"लिंक की जाँच",dis_owner:"लिंक का असली मालिक",sec_cmp:"लिंक की तुलना",cmp_fake:"संदेश में लिंक",cmp_real:"«{b}» की आधिकारिक साइट",how:"फ़तिन ने कैसे तय किया?",
  btn_listen:"सुनें",btn_report:"रिपोर्ट",btn_trust:"भरोसेमंद व्यक्ति को भेजें",p_link:"लिंक न खोलें",p_code:"कोड न दें",p_money:"पैसे न भेजें",p_reply:"जवाब न दें",p_family:"परिवार से पूछें",p_ok:"सुरक्षित",p_nocode:"अपना कोड किसी को न दें",
  speak_pre:"फ़तिन कहता है: यह संदेश ",speak_why:" कारण: ",panic:"धोखा हो गया?",qr_title_d:"खतरा: लिंक बंद करें",qr_title_s:"संदिग्ध लिंक",qr_title_ok:"सुरक्षित लगता है",qr_sub:"इस QR कोड के अंदर:",qr_close:"लिंक बंद करें",qr_open:"लिंक खोलें",qr_none:"QR कोड नहीं मिला। साफ़ फ़ोटो लें।",ask_ph:"फ़तिन से कुछ भी पूछें…",lang_note:"मुख्य स्क्रीन का अनुवाद हो गया है। अभ्यास स्क्रीन अभी अरबी में हैं।"};
T.bn={tab_scan:"যাচাই",tab_sim:"বার্তা",tab_call:"কল",tab_train:"অনুশীলন",tab_more:"আরও",sub_scan:"প্রতারণার বিরুদ্ধে আপনার স্মার্ট ঢাল",
  h_scan:"যেকোনো বার্তা<br>ক্লিক করার আগে যাচাই করুন",sub_scan2:"SMS, WhatsApp বা ইমেইল",lbl_msg:"আপনার পাওয়া বার্তা",ph_msg:"এখানে বার্তা পেস্ট করুন…",btn_scan:"বার্তা যাচাই করুন",btn_qr:"QR স্ক্যান",
  safe_t:"নিরাপদ মনে হচ্ছে",safe_s:"স্পষ্ট কোনো বিপদ নেই। তবুও কাউকে কোড দেবেন না।",suspicious_t:"সন্দেহজনক",suspicious_s:"সাবধান। নিশ্চিত না হয়ে কোনো লিংকে ক্লিক করবেন না।",danger_t:"বিপদ",danger_s:"লিংক খুলবেন না, উত্তর দেবেন না, কোনো কোড দেবেন না।",
  word_safe:"নিরাপদ",word_suspicious:"সন্দেহজনক",word_danger:"বিপজ্জনক",v_example:"উদাহরণ · একটি উদাহরণ বেছে নিন বা আপনার বার্তা পেস্ট করুন",v_quick:"আপনার ফোনে দ্রুত যাচাই",v_two:"দুই স্তরের যাচাইয়ের পর",
  sec_msg:"আপনার বার্তা, আর ফাতিন যা ধরেছে",lg1:"বিপদ",lg2:"নকল নাম",lg3:"নিরাপত্তা চিহ্ন",sec_dis:"লিংক বিশ্লেষণ",dis_owner:"লিংকের আসল মালিক",sec_cmp:"লিংক তুলনা",cmp_fake:"বার্তার লিংক",cmp_real:"«{b}»-এর অফিসিয়াল সাইট",how:"ফাতিন কীভাবে সিদ্ধান্ত নিল?",
  btn_listen:"শুনুন",btn_report:"রিপোর্ট",btn_trust:"বিশ্বস্ত কাউকে পাঠান",p_link:"লিংক খুলবেন না",p_code:"কোড দেবেন না",p_money:"টাকা পাঠাবেন না",p_reply:"উত্তর দেবেন না",p_family:"পরিবারকে জিজ্ঞেস করুন",p_ok:"নিরাপদ",p_nocode:"কাউকে কোড দেবেন না",
  speak_pre:"ফাতিন বলছে: বার্তাটি ",speak_why:" কারণ: ",panic:"প্রতারিত হয়েছেন?",qr_title_d:"বিপদ: লিংক বন্ধ করুন",qr_title_s:"সন্দেহজনক লিংক",qr_title_ok:"নিরাপদ মনে হচ্ছে",qr_sub:"এই QR কোডের ভিতরে:",qr_close:"লিংক বন্ধ করুন",qr_open:"লিংক খুলুন",qr_none:"QR কোড পাওয়া যায়নি। পরিষ্কার ছবি তুলুন।",ask_ph:"ফাতিনকে যেকোনো প্রশ্ন করুন…",lang_note:"প্রধান স্ক্রিন অনুবাদ করা হয়েছে। অনুশীলন স্ক্রিন এখনো আরবিতে।"};
T.id={tab_scan:"Periksa",tab_sim:"Pesan",tab_call:"Panggilan",tab_train:"Latihan",tab_more:"Lainnya",sub_scan:"Perisai pintar Anda melawan penipuan",
  h_scan:"Periksa pesan apa pun<br>sebelum mengeklik",sub_scan2:"SMS, WhatsApp, atau email",lbl_msg:"Pesan yang Anda terima",ph_msg:"Tempel pesan di sini…",btn_scan:"Periksa pesan",btn_qr:"Pindai QR",
  safe_t:"Tampak aman",safe_s:"Tidak ada bahaya jelas. Tetap jangan berikan kode Anda kepada siapa pun.",suspicious_t:"Mencurigakan",suspicious_s:"Hati-hati. Jangan klik tautan sebelum yakin.",danger_t:"Bahaya",danger_s:"Jangan klik tautan, jangan membalas, dan jangan berikan kode apa pun.",
  word_safe:"aman",word_suspicious:"mencurigakan",word_danger:"berbahaya",v_example:"Contoh · pilih contoh atau tempel pesan Anda",v_quick:"Pemeriksaan cepat di ponsel Anda",v_two:"Setelah dua lapis pemeriksaan",
  sec_msg:"Pesan Anda, dan yang ditemukan Fatin",lg1:"Bahaya",lg2:"Nama palsu",lg3:"Tanda aman",sec_dis:"Bedah tautan",dis_owner:"Pemilik asli tautan",sec_cmp:"Bandingkan tautan",cmp_fake:"Tautan di pesan",cmp_real:"Situs resmi «{b}»",how:"Bagaimana Fatin memutuskan?",
  btn_listen:"Dengarkan",btn_report:"Laporkan",btn_trust:"Kirim ke orang tepercaya",p_link:"Jangan klik tautan",p_code:"Jangan beri kode",p_money:"Jangan kirim uang",p_reply:"Jangan membalas",p_family:"Tanya keluarga",p_ok:"Aman",p_nocode:"Jangan bagikan kode",
  speak_pre:"Kata Fatin: pesan ini ",speak_why:" Alasan: ",panic:"Kena tipu?",qr_title_d:"Bahaya: tutup tautan",qr_title_s:"Tautan mencurigakan",qr_title_ok:"Tampak aman",qr_sub:"Isi kode QR ini:",qr_close:"Tutup tautan",qr_open:"Buka tautan",qr_none:"Kode QR tidak ditemukan. Ambil foto yang lebih jelas.",ask_ph:"Tanya Fatin apa saja…",lang_note:"Layar utama sudah diterjemahkan. Layar latihan masih berbahasa Arab."};
T.zh={tab_scan:"检测",tab_sim:"短信",tab_call:"来电",tab_train:"练习",tab_more:"更多",sub_scan:"您的智能反诈盾牌",
  h_scan:"点击之前<br>先检测任何消息",sub_scan2:"短信、WhatsApp 或邮件",lbl_msg:"您收到的消息",ph_msg:"在此粘贴消息…",btn_scan:"检测消息",btn_qr:"扫描二维码",
  safe_t:"看起来安全",safe_s:"没有明显危险。但永远不要把验证码告诉任何人。",suspicious_t:"可疑",suspicious_s:"小心。确认之前不要点击任何链接。",danger_t:"危险",danger_s:"不要点击链接，不要回复，也不要提供任何验证码。",
  word_safe:"安全",word_suspicious:"可疑",word_danger:"危险",v_example:"示例 · 点选示例或粘贴您的消息",v_quick:"在您手机上快速检测",v_two:"经过两层检测",
  sec_msg:"您的消息，以及 Fatin 发现的问题",lg1:"危险",lg2:"冒用名称",lg3:"安全信号",sec_dis:"链接剖析",dis_owner:"链接的真正所有者",sec_cmp:"对比链接",cmp_fake:"消息中的链接",cmp_real:"«{b}» 官方网站",how:"Fatin 如何判断？",
  btn_listen:"朗读",btn_report:"举报",btn_trust:"发给我信任的人",p_link:"不要点链接",p_code:"不要给验证码",p_money:"不要转账",p_reply:"不要回复",p_family:"问问家人",p_ok:"安全",p_nocode:"不要泄露验证码",
  speak_pre:"Fatin 提醒：这条消息",speak_why:"。原因：",panic:"被骗了？",qr_title_d:"危险：关闭链接",qr_title_s:"可疑链接",qr_title_ok:"看起来安全",qr_sub:"二维码里的内容：",qr_close:"关闭链接",qr_open:"打开链接",qr_none:"没有找到二维码，请拍得更清楚些。",ask_ph:"向 Fatin 提问…",lang_note:"主要页面已翻译，练习页面暂为阿拉伯语。"};
T.es={tab_scan:"Revisar",tab_sim:"Mensajes",tab_call:"Llamada",tab_train:"Práctica",tab_more:"Más",sub_scan:"Tu escudo inteligente contra estafas",
  h_scan:"Revisa cualquier mensaje<br>antes de tocar",sub_scan2:"SMS, WhatsApp o correo",lbl_msg:"El mensaje que recibiste",ph_msg:"Pega aquí el mensaje…",btn_scan:"Revisar mensaje",btn_qr:"Escanear QR",
  safe_t:"Parece seguro",safe_s:"Sin peligro claro. Aun así, nunca compartas tus códigos.",suspicious_t:"Sospechoso",suspicious_s:"Cuidado. No toques ningún enlace hasta estar seguro.",danger_t:"Peligro",danger_s:"No abras el enlace, no respondas y no des ningún código.",
  word_safe:"seguro",word_suspicious:"sospechoso",word_danger:"peligroso",v_example:"Ejemplo · elige un ejemplo o pega tu mensaje",v_quick:"Revisión rápida en tu teléfono",v_two:"Tras dos capas de revisión",
  sec_msg:"Tu mensaje y lo que detectó Fatin",lg1:"Peligro",lg2:"Nombre suplantado",lg3:"Señal segura",sec_dis:"Análisis del enlace",dis_owner:"El verdadero dueño del enlace",sec_cmp:"Compara el enlace",cmp_fake:"Enlace del mensaje",cmp_real:"Sitio oficial de «{b}»",how:"¿Cómo decidió Fatin?",
  btn_listen:"Escuchar",btn_report:"Denunciar",btn_trust:"Enviar a alguien de confianza",p_link:"No abras el enlace",p_code:"No des el código",p_money:"No envíes dinero",p_reply:"No respondas",p_family:"Pregunta a tu familia",p_ok:"Seguro",p_nocode:"Nunca compartas tu código",
  speak_pre:"Fatin dice: el mensaje es ",speak_why:" Motivo: ",panic:"¿Te estafaron?",qr_title_d:"Peligro: cierra el enlace",qr_title_s:"Enlace sospechoso",qr_title_ok:"Parece seguro",qr_sub:"Contenido de este código QR:",qr_close:"Cerrar el enlace",qr_open:"Abrir el enlace",qr_none:"No se encontró ningún código QR. Toma una foto más nítida.",ask_ph:"Pregúntale a Fatin…",lang_note:"Las pantallas principales están traducidas. La práctica sigue en árabe por ahora."};
T.fr={tab_scan:"Vérifier",tab_sim:"Messages",tab_call:"Appel",tab_train:"Exercices",tab_more:"Plus",sub_scan:"Votre bouclier intelligent contre les arnaques",
  h_scan:"Vérifiez chaque message<br>avant de cliquer",sub_scan2:"SMS, WhatsApp ou e-mail",lbl_msg:"Le message reçu",ph_msg:"Collez le message ici…",btn_scan:"Vérifier le message",btn_qr:"Scanner un QR",
  safe_t:"Semble sûr",safe_s:"Aucun danger évident. Ne partagez jamais vos codes pour autant.",suspicious_t:"Suspect",suspicious_s:"Prudence. Ne cliquez sur aucun lien avant d'être sûr.",danger_t:"Danger",danger_s:"N'ouvrez pas le lien, ne répondez pas et ne donnez aucun code.",
  word_safe:"sûr",word_suspicious:"suspect",word_danger:"dangereux",v_example:"Exemple · choisissez un exemple ou collez votre message",v_quick:"Vérification rapide sur votre téléphone",v_two:"Après deux niveaux de vérification",
  sec_msg:"Votre message, et ce que Fatin a repéré",lg1:"Danger",lg2:"Nom usurpé",lg3:"Signe rassurant",sec_dis:"Analyse du lien",dis_owner:"Le vrai propriétaire du lien",sec_cmp:"Comparer le lien",cmp_fake:"Lien du message",cmp_real:"Site officiel de «{b}»",how:"Comment Fatin a-t-il décidé ?",
  btn_listen:"Écouter",btn_report:"Signaler",btn_trust:"Envoyer à un proche de confiance",p_link:"N'ouvrez pas le lien",p_code:"Ne donnez pas le code",p_money:"N'envoyez pas d'argent",p_reply:"Ne répondez pas",p_family:"Demandez à votre famille",p_ok:"Sûr",p_nocode:"Ne partagez jamais votre code",
  speak_pre:"Fatin dit : le message est ",speak_why:" Raison : ",panic:"Victime d'arnaque ?",qr_title_d:"Danger : fermez le lien",qr_title_s:"Lien suspect",qr_title_ok:"Semble sûr",qr_sub:"Contenu de ce QR code :",qr_close:"Fermer le lien",qr_open:"Ouvrir le lien",qr_none:"Aucun QR code trouvé. Prenez une photo plus nette.",ask_ph:"Posez une question à Fatin…",lang_note:"Les écrans principaux sont traduits. Les exercices restent en arabe pour l'instant."};
R.hi={otp:"आपसे सत्यापन कोड माँग रहा है। सरकारी संस्थाएँ कभी कोड नहीं माँगतीं।",card:"आपके कार्ड का विवरण या पासवर्ड माँग रहा है।",suspend:"आपका खाता या सेवा बंद करने की धमकी दे रहा है।",urgent:"जल्दबाज़ी करवा रहा है ताकि आप सोचें नहीं।",prize:"ऐसे इनाम का वादा जिसमें आपने हिस्सा ही नहीं लिया।",update:"लिंक के ज़रिए जानकारी अपडेट करने को कह रहा है।",ship:"डिलीवरी शुल्क माँग रहा है। कूरियर कंपनियाँ लिंक से भुगतान नहीं माँगतीं।",invest:"आसान और पक्के मुनाफ़े का वादा।",newnum:"नए नंबर से रिश्तेदार होने का दावा। पुराने नंबर पर फ़ोन करके पुष्टि करें।",money:"पैसे भेजने या भुगतान करने को कह रहा है।",nafath:"नफ़ाज़ अनुरोध स्वीकार करने को कह रहा है। इससे आपके सरकारी खाते खुल जाते हैं।",remote:"आपका फ़ोन दूर से नियंत्रित करना चाहता है। कोई ऐप इंस्टॉल न करें।",giftcard:"गिफ़्ट कार्ड और उनके कोड माँग रहा है।",login:"लिंक के ज़रिए लॉग इन या जानकारी माँग रहा है।",sensdata:"पहचान या बैंक खाते जैसी संवेदनशील जानकारी माँग रहा है।",short:"छोटा किया गया लिंक जो असली मंज़िल छिपाता है।",imp:"किसी जानी-मानी संस्था का नाम इस्तेमाल कर रहा है, पर लिंक उसकी आधिकारिक साइट नहीं।",lookalike:"लिंक किसी जाने-माने नाम की नकल है, आधिकारिक साइट नहीं।",badlink:"लिंक भरोसेमंद नहीं लगता।",link:"अनजान साइट का लिंक है। पक्का न हो तो न खोलें।",official:"लिंक आधिकारिक लगता है, फिर भी खुद आधिकारिक ऐप खोलें।",safehint:"यह कोड साझा न करने की चेतावनी देता है, जैसे आधिकारिक संदेश करते हैं।",qrpay:"यह QR अनौपचारिक साइट के भुगतान पेज पर ले जाता है। सिर्फ़ आधिकारिक ऐप से भुगतान करें।",none:"धोखाधड़ी का कोई स्पष्ट संकेत नहीं मिला।"};
R.bn={otp:"আপনার কাছে যাচাই কোড চাইছে। সরকারি প্রতিষ্ঠান কখনো কোড চায় না।",card:"আপনার কার্ডের তথ্য বা পাসওয়ার্ড চাইছে।",suspend:"আপনার অ্যাকাউন্ট বা সেবা বন্ধ করার হুমকি দিচ্ছে।",urgent:"তাড়াহুড়ো করাচ্ছে যাতে আপনি ভাবার সময় না পান।",prize:"এমন পুরস্কারের প্রতিশ্রুতি যাতে আপনি অংশই নেননি।",update:"লিংকের মাধ্যমে তথ্য আপডেট করতে বলছে।",ship:"ডেলিভারি ফি চাইছে। কুরিয়ার কোম্পানি লিংকে টাকা চায় না।",invest:"সহজ ও নিশ্চিত লাভের প্রতিশ্রুতি।",newnum:"নতুন নম্বর থেকে আত্মীয় সেজেছে। পুরোনো নম্বরে ফোন করে নিশ্চিত হন।",money:"টাকা পাঠাতে বা পরিশোধ করতে বলছে।",nafath:"নাফাথ অনুরোধ অনুমোদন করতে বলছে। এতে আপনার সরকারি অ্যাকাউন্ট খুলে যায়।",remote:"দূর থেকে আপনার ফোন নিয়ন্ত্রণ করতে চায়। কোনো অ্যাপ ইনস্টল করবেন না।",giftcard:"গিফট কার্ড ও তার কোড চাইছে।",login:"লিংকের মাধ্যমে লগইন বা তথ্য চাইছে।",sensdata:"পরিচয়পত্র বা ব্যাংক অ্যাকাউন্টের মতো সংবেদনশীল তথ্য চাইছে।",short:"ছোট করা লিংক, আসল ঠিকানা লুকিয়ে রাখে।",imp:"পরিচিত প্রতিষ্ঠানের নাম ব্যবহার করছে, কিন্তু লিংকটি তাদের অফিসিয়াল সাইট নয়।",lookalike:"লিংকটি পরিচিত নামের নকল, অফিসিয়াল সাইট নয়।",badlink:"লিংকটি বিশ্বাসযোগ্য মনে হচ্ছে না।",link:"অজানা সাইটের লিংক। নিশ্চিত না হলে খুলবেন না।",official:"লিংকটি অফিসিয়াল মনে হচ্ছে, তবুও নিজে অফিসিয়াল অ্যাপ খুলুন।",safehint:"এটি কোড শেয়ার না করতে সতর্ক করে, যেমন অফিসিয়াল বার্তা করে।",qrpay:"এই QR অনানুষ্ঠানিক সাইটের পেমেন্ট পেজে নিয়ে যায়। শুধু অফিসিয়াল অ্যাপে পরিশোধ করুন।",none:"প্রতারণার কোনো স্পষ্ট লক্ষণ পাওয়া যায়নি।"};
R.id={otp:"Meminta kode verifikasi Anda. Instansi resmi tidak pernah memintanya.",card:"Meminta detail kartu atau kata sandi Anda.",suspend:"Mengancam akan memblokir akun atau layanan Anda.",urgent:"Membuat Anda terburu-buru agar tidak berpikir.",prize:"Menjanjikan hadiah dari undian yang tidak pernah Anda ikuti.",update:"Meminta Anda memperbarui data lewat tautan.",ship:"Meminta biaya pengiriman. Kurir tidak menagih lewat tautan di SMS.",invest:"Menjanjikan untung mudah dan pasti.",newnum:"Mengaku kerabat dengan nomor baru. Telepon nomor lamanya untuk memastikan.",money:"Meminta Anda mentransfer atau membayar uang.",nafath:"Meminta Anda menyetujui permintaan Nafath. Itu membuka akun pemerintah Anda.",remote:"Ingin mengendalikan ponsel Anda dari jauh. Jangan pasang aplikasi apa pun.",giftcard:"Meminta kartu hadiah dan kodenya.",login:"Meminta Anda masuk atau mengisi data lewat tautan.",sensdata:"Meminta data sensitif seperti identitas atau rekening bank.",short:"Tautan pendek yang menyembunyikan tujuan sebenarnya.",imp:"Memakai nama lembaga terkenal, tetapi tautannya bukan situs resminya.",lookalike:"Tautan meniru nama terkenal, bukan situs resmi.",badlink:"Tautan tampak tidak tepercaya.",link:"Tautan ke situs tak dikenal. Jangan buka jika tidak yakin.",official:"Tautan tampak resmi, tetap buka aplikasi resminya sendiri.",safehint:"Pesan ini memperingatkan agar tidak membagikan kode, seperti pesan resmi.",qrpay:"QR ini mengarah ke halaman pembayaran di situs tidak resmi. Bayar hanya lewat aplikasi resmi.",none:"Tidak ada tanda penipuan yang jelas."};
R.zh={otp:"索要您的验证码。官方机构从不索要验证码。",card:"索要您的银行卡信息或密码。",suspend:"威胁要冻结您的账户或服务。",urgent:"催促您，让您来不及思考。",prize:"承诺您从未参加过的抽奖奖品。",update:"要求您通过链接更新资料。",ship:"索要运费。快递公司不会通过短信链接收费。",invest:"承诺轻松、稳赚的收益。",newnum:"用新号码冒充亲人。请拨打对方旧号码核实。",money:"要求您转账或付款。",nafath:"要求您批准 Nafath 请求，这会打开您的政府账户。",remote:"想远程控制您的手机。不要安装任何应用。",giftcard:"索要礼品卡及其卡密。",login:"要求您通过链接登录或填写信息。",sensdata:"索要身份证件或银行账户等敏感信息。",short:"短链接，隐藏真实去向。",imp:"冒用知名机构的名义，但链接不是其官网。",lookalike:"链接仿冒知名名称，并非官网。",badlink:"链接看起来不可信。",link:"指向未知网站的链接。不确定就不要打开。",official:"链接看似官方，但仍请自己打开官方应用。",safehint:"提醒您不要泄露验证码，这是官方消息的做法。",qrpay:"该二维码指向非官方网站的付款页面。请只在官方应用中付款。",none:"未发现明显的诈骗迹象。"};
R.es={otp:"Pide tu código de verificación. Ninguna entidad oficial lo pide.",card:"Pide los datos de tu tarjeta o tu contraseña.",suspend:"Amenaza con suspender tu cuenta o servicios.",urgent:"Te apura para que no pienses.",prize:"Promete un premio de un sorteo en el que nunca participaste.",update:"Te pide actualizar tus datos mediante un enlace.",ship:"Pide una tarifa de envío. Las empresas de mensajería no cobran por enlaces en SMS.",invest:"Promete ganancias fáciles y garantizadas.",newnum:"Dice ser un familiar con número nuevo. Llama a su número anterior para confirmar.",money:"Te pide transferir o pagar dinero.",nafath:"Te pide aprobar una solicitud de Nafath. Eso abre tus cuentas del gobierno.",remote:"Quiere controlar tu teléfono a distancia. No instales nada.",giftcard:"Pide tarjetas regalo y sus códigos.",login:"Te pide iniciar sesión o dar datos en un enlace.",sensdata:"Pide datos sensibles como tu documento o cuenta bancaria.",short:"Enlace acortado que oculta su destino real.",imp:"Usa el nombre de una entidad conocida, pero el enlace no es su sitio oficial.",lookalike:"El enlace imita un nombre conocido, pero no es oficial.",badlink:"El enlace no parece confiable.",link:"Enlace a un sitio desconocido. No lo abras si no estás seguro.",official:"El enlace parece oficial; aun así, abre tú mismo la app oficial.",safehint:"Advierte que no compartas el código, como hacen los mensajes oficiales.",qrpay:"Este QR lleva a una página de pago no oficial. Paga solo en la app oficial.",none:"No se encontraron señales claras de estafa."};
R.fr={otp:"Demande votre code de vérification. Aucun organisme officiel ne le demande.",card:"Demande vos données de carte ou votre mot de passe.",suspend:"Menace de bloquer votre compte ou vos services.",urgent:"Vous presse pour que vous ne réfléchissiez pas.",prize:"Promet un gain à un tirage auquel vous n'avez jamais participé.",update:"Vous demande de mettre à jour vos données via un lien.",ship:"Réclame des frais de livraison. Les transporteurs ne font pas payer par lien SMS.",invest:"Promet des gains faciles et garantis.",newnum:"Se fait passer pour un proche avec un nouveau numéro. Appelez son ancien numéro.",money:"Vous demande d'envoyer ou de payer de l'argent.",nafath:"Vous demande d'approuver une demande Nafath, ce qui ouvre vos comptes publics.",remote:"Veut contrôler votre téléphone à distance. N'installez rien.",giftcard:"Réclame des cartes cadeaux et leurs codes.",login:"Vous demande de vous connecter ou de saisir des données via un lien.",sensdata:"Demande des données sensibles comme votre pièce d'identité ou votre compte.",short:"Lien raccourci qui cache sa vraie destination.",imp:"Utilise le nom d'un organisme connu, mais le lien n'est pas son site officiel.",lookalike:"Le lien imite un nom connu mais n'est pas officiel.",badlink:"Le lien ne semble pas fiable.",link:"Lien vers un site inconnu. Ne l'ouvrez pas sans certitude.",official:"Le lien semble officiel ; ouvrez quand même l'application officielle vous-même.",safehint:"Il vous avertit de ne pas partager le code, comme le font les messages officiels.",qrpay:"Ce QR mène à une page de paiement non officielle. Payez uniquement dans l'application officielle.",none:"Aucun signe clair d'arnaque."};
Object.assign(EX_L,{
  hi:[["इकामा धमकी","आपका इकामा ब्लॉक कर दिया गया है। तुरंत सत्यापित करें: iqama-check.xyz"],["कोड माँगना","मैं बैंक से बोल रहा हूँ, आपको जो ओटीपी मिला है वह भेजें"],["इनाम","बधाई हो! आपने 10,000 रियाल जीते हैं। यहाँ क्लिक करें: prize-ksa.top"],["सुरक्षित","आपका ओटीपी 4821 है। इसे किसी से साझा न करें।"]],
  bn:[["ইকামা হুমকি","আপনার ইকামা ব্লক করা হয়েছে, এখনই যাচাই করুন: iqama-check.xyz"],["কোড চাওয়া","আমি ব্যাংক থেকে বলছি, আপনার ফোনে যে ওটিপি এসেছে তা পাঠান"],["পার্সেল ফি","আপনার পার্সেল আটকে আছে, এখনই ১২ রিয়াল ফি পরিশোধ করুন: spl-delivery.info"],["নিরাপদ","আপনার ওটিপি 4821। কাউকে শেয়ার করবেন না।"]],
  id:[["Hadiah palsu","Selamat! Anda menang hadiah 5.000 SAR. Klik di sini: prize-ksa.top"],["Minta kode","Saya dari bank, tolong kirimkan kode OTP yang Anda terima untuk membatalkan transaksi"],["Biaya paket","Paket Anda tertahan, bayar biaya 12 SAR segera: spl-delivery.info"],["Aman","Kode OTP Anda 4821. Jangan bagikan kepada siapa pun."]],
  zh:[["冒充银行","您好，我是银行客服，请把您收到的验证码发给我，以便取消交易"],["中奖诈骗","恭喜您中奖 10000 里亚尔！点击领取：prize-ksa.top"],["包裹费用","您的包裹被扣留，请立即支付 12 里亚尔关税：spl-delivery.info"],["安全","您的验证码是 4821，请勿告诉他人。"]],
  es:[["Premio falso","¡Felicidades! Has ganado 5.000 SAR. Haz clic aquí: prize-ksa.top"],["Pide código","Hola, soy del banco. Envíame el código que recibiste para cancelar la operación"],["Paquete","Tu paquete está retenido. Paga 12 SAR de aduana ahora: spl-delivery.info"],["Seguro","Tu código es 4821. No lo compartas con nadie."]],
  fr:[["Faux gain","Félicitations ! Vous avez gagné 5 000 SAR. Cliquez ici : prize-ksa.top"],["Demande de code","Bonjour, ici votre banque. Envoyez-moi le code reçu pour annuler l'opération"],["Colis","Votre colis est bloqué. Payez 12 SAR de frais de douane : spl-delivery.info"],["Sûr","Votre code est 4821. Ne le partagez avec personne."]]
});
Object.assign(GREET,{hi:["फिर से स्वागत है, {n}","नमस्ते, {n}","सुरक्षित रहें, {n}"],bn:["আবার স্বাগতম, {n}","হ্যালো, {n}","নিরাপদ থাকুন, {n}"],id:["Selamat datang kembali, {n}","Halo, {n}","Tetap aman, {n}"],zh:["欢迎回来，{n}","你好，{n}","注意安全，{n}"],es:["Bienvenido de nuevo, {n}","Hola, {n}","Cuídate hoy, {n}"],fr:["Bon retour, {n}","Bonjour, {n}","Restez prudent, {n}"]});
Object.assign(ASK_SUG,{hi:["क्या बैंक कभी कोड माँगता है?","नफ़ाज़ क्या है?","पार्सल फ़ीस का लिंक आया है, क्या करूँ?"],bn:["ব্যাংক কি কোড চায়?","নাফাথ কী?","পার্সেল ফি-র লিংক এসেছে, কী করব?"],id:["Apakah bank pernah minta kode?","Apa itu Nafath?","Ada tautan biaya paket, harus bagaimana?"],zh:["银行会索要验证码吗？","Nafath 是什么？","收到包裹费用链接怎么办？"],es:["¿El banco pide códigos?","¿Qué es Nafath?","Me llegó un enlace de pago de paquete, ¿qué hago?"],fr:["La banque demande-t-elle des codes ?","Qu'est-ce que Nafath ?","J'ai reçu un lien de frais de colis, que faire ?"]});

/* the device decides the first language: its UI language, then its region */
function deviceLang(){
  try{
    const prefs=(navigator.languages&&navigator.languages.length?navigator.languages:[navigator.language||""]).map(x=>String(x).toLowerCase());
    for(const p of prefs){ const b=p.split("-")[0]; if(b==="fil"||b==="tl") return "tl"; if(b==="in") return "id"; if(LANGS[b]) return b; }
    const tz=(Intl.DateTimeFormat().resolvedOptions().timeZone||"");
    const TZ={"Asia/Karachi":"ur","Asia/Kolkata":"hi","Asia/Calcutta":"hi","Asia/Dhaka":"bn","Asia/Manila":"tl","Asia/Jakarta":"id","Asia/Makassar":"id","Asia/Shanghai":"zh","Asia/Hong_Kong":"zh","Asia/Taipei":"zh","Europe/Madrid":"es","America/Mexico_City":"es","Europe/Paris":"fr","Africa/Casablanca":"ar","Asia/Riyadh":"ar","Asia/Dubai":"ar","Asia/Kuwait":"ar","Asia/Qatar":"ar","Asia/Bahrain":"ar","Africa/Cairo":"ar"};
    if(TZ[tz]) return TZ[tz];
    const reg=(prefs[0].split("-")[1]||"").toUpperCase();
    const RG={PK:"ur",IN:"hi",BD:"bn",PH:"tl",ID:"id",CN:"zh",TW:"zh",ES:"es",MX:"es",FR:"fr",SA:"ar",AE:"ar",EG:"ar"};
    if(RG[reg]) return RG[reg];
  }catch(e){}
  return "en";
}
if(S.get("lang",null)===null) lang=deviceLang();

/* globe menu */
function drawLangSheet(){
  const box=$("lang-list"); box.innerHTML="";
  LANG_ORDER.forEach(k=>{ const b=el("button","lang-opt"); b.dataset.lang=k; b.setAttribute("aria-pressed",String(k===lang)); b.appendChild(el("b","",LANGS[k].name)); b.appendChild(el("small","",LANGS[k].en)); b.onclick=()=>{ applyLang(k); closeLangSheet(); }; box.appendChild(b); });
}
function openLangSheet(){ drawLangSheet(); $("lang-sheet").classList.add("on"); $("lang-scrim").classList.add("on"); }
openLangSheet=hookable("openLangSheet",openLangSheet);
function closeLangSheet(){ $("lang-sheet").classList.remove("on"); $("lang-scrim").classList.remove("on"); }
closeLangSheet=hookable("closeLangSheet",closeLangSheet);
document.querySelectorAll(".globe").forEach(b=>b.onclick=openLangSheet);
$("lang-scrim").onclick=closeLangSheet; $("lang-done").onclick=closeLangSheet;

/* sign-in screen in every language: [title, subtitle, name, placeholder, address-as, male, female, enter, or, nafath, soon, safety note, err-name, err-gender] */
const LI_T={
 en:["Welcome to Fatin","Tell us your name so we can greet you properly.","Your name","e.g. Hassan","I am","Man","Woman","Enter","or","Sign in with Nafath","Soon","<b>Fatin never asks for your ID number.</b> If anyone asks for it in Fatin's name, it's a scam. Your name stays on your device only.","Type your name so we can greet you.","Choose Mr or Ms."],
 ur:["فطن میں خوش آمدید","اپنا نام بتائیں تاکہ ہم آپ کا صحیح استقبال کریں۔","آپ کا نام","مثلاً: حسن","میں ہوں","مرد","عورت","داخل ہوں","یا","نفاذ کے ذریعے داخلہ","جلد","<b>فطن کبھی آپ کا شناختی نمبر نہیں مانگتا۔</b> اگر کوئی فطن کے نام پر مانگے تو وہ دھوکے باز ہے۔ آپ کا نام صرف آپ کے فون میں رہتا ہے۔","اپنا نام لکھیں۔","بھائی یا بہن منتخب کریں۔"],
 hi:["फ़तिन में आपका स्वागत है","अपना नाम बताएँ ताकि हम आपका सही स्वागत करें।","आपका नाम","जैसे: रवि","मैं हूँ","पुरुष","महिला","प्रवेश करें","या","नफ़ाज़ से साइन इन","जल्द","<b>फ़तिन कभी आपका पहचान नंबर नहीं माँगता।</b> अगर कोई फ़तिन के नाम पर माँगे तो वह धोखेबाज़ है। आपका नाम सिर्फ़ आपके फ़ोन में रहता है।","अपना नाम लिखें।","भाई या बहन चुनें।"],
 bn:["ফাতিনে স্বাগতম","আপনার নাম বলুন যাতে আমরা ঠিকভাবে স্বাগত জানাতে পারি।","আপনার নাম","যেমন: রহিম","আমি","পুরুষ","নারী","প্রবেশ করুন","অথবা","নাফাথ দিয়ে সাইন ইন","শীঘ্রই","<b>ফাতিন কখনো আপনার পরিচয় নম্বর চায় না।</b> কেউ ফাতিনের নামে চাইলে সে প্রতারক। আপনার নাম শুধু আপনার ফোনেই থাকে।","আপনার নাম লিখুন।","ভাই বা বোন বেছে নিন।"],
 tl:["Maligayang pagdating sa Fatin","Sabihin ang pangalan mo para mabati ka namin nang tama.","Pangalan mo","hal. Maria","Ako ay","Lalaki","Babae","Pumasok","o","Mag-sign in gamit ang Nafath","Malapit na","<b>Hindi kailanman hihingin ng Fatin ang ID number mo.</b> Kung may humingi nito gamit ang pangalan ng Fatin, scam iyon. Nasa phone mo lang ang pangalan mo.","Isulat ang pangalan mo.","Pumili: Kuya o Ate."],
 id:["Selamat datang di Fatin","Beri tahu nama Anda agar kami bisa menyapa dengan benar.","Nama Anda","mis. Siti","Saya","Laki-laki","Perempuan","Masuk","atau","Masuk dengan Nafath","Segera","<b>Fatin tidak pernah meminta nomor identitas Anda.</b> Jika ada yang memintanya atas nama Fatin, itu penipuan. Nama Anda hanya tersimpan di ponsel Anda.","Tulis nama Anda.","Pilih panggilan Anda."],
 zh:["欢迎使用 Fatin","告诉我们您的名字，方便我们称呼您。","您的名字","例如：小明","我是","男","女","进入","或","使用 Nafath 登录","即将推出","<b>Fatin 绝不会索要您的身份证号。</b>如有人以 Fatin 名义索要，那就是诈骗。您的名字只保存在您的手机上。","请输入您的名字。","请选择称呼。"],
 es:["Bienvenido a Fatin","Dinos tu nombre para saludarte como se debe.","Tu nombre","p. ej. Lucía","Soy","Hombre","Mujer","Entrar","o","Entrar con Nafath","Pronto","<b>Fatin nunca te pide tu número de identidad.</b> Si alguien te lo pide en nombre de Fatin, es una estafa. Tu nombre se queda solo en tu teléfono.","Escribe tu nombre.","Elige cómo tratarte."],
 fr:["Bienvenue dans Fatin","Dites-nous votre prénom pour bien vous accueillir.","Votre prénom","ex. Amine","Je suis","Homme","Femme","Entrer","ou","Se connecter avec Nafath","Bientôt","<b>Fatin ne demande jamais votre numéro d'identité.</b> Si quelqu'un le demande au nom de Fatin, c'est une arnaque. Votre prénom reste uniquement sur votre téléphone.","Écrivez votre prénom.","Choisissez Monsieur ou Madame."]
};
const LI_SEL=[["#login h2","text"],["#login .sub","text"],['label[for="li-name"]',"text"],["#li-name","ph"],["#li-form > span.label","text"],['#li-g [data-g="m"]',"text"],['#li-g [data-g="f"]',"text"],['#li-form button[type="submit"]',"text"],[".li-or span","text"],["#li-nafath b","text"],["#li-nafath em","text"],[".li-safe","html"]];
const LI_AR=LI_SEL.map(([s,k])=>{ const n=document.querySelector(s); return !n?"":k==="ph"?n.placeholder:k==="html"?n.innerHTML:n.textContent; });
function applyLoginLang(){
  const L=lang==="ar"?LI_AR:(LI_T[lang]||LI_T.en);
  LI_SEL.forEach(([s,k],i)=>{ const n=document.querySelector(s); if(!n) return; if(k==="ph") n.placeholder=L[i]; else if(k==="html") n.innerHTML=L[i]; else n.textContent=L[i]; });
  $("li-naf-info").hidden=true; $("li-err").textContent="";
}
hook("after","applyLang",()=>{ try{ applyLoginLang(); }catch(e){} });

