// Copies the third-party files the app serves itself (no CDN at run time) from pinned npm packages.
//
//   node tools/vendor.mjs          write app/vendor/* and app/fonts/*
//   node tools/vendor.mjs --check  fail if the committed copies differ from the pinned packages (CI)
//
// app/vendor/qrcode.min.js  qrcodejs 1.0.0 (MIT, davidshimjs)          draws the "open the app" QR code
// app/vendor/jsQR.min.js    jsqr 1.4.0 (Apache-2.0), minified here     reads QR codes from photos
// app/fonts/*               Alexandria and IBM Plex Sans Arabic (OFL-1.1), Arabic + Latin subsets
import { readFileSync, writeFileSync, mkdirSync, existsSync, readdirSync } from "node:fs";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";
import { transformSync } from "esbuild";

const ROOT = join(dirname(fileURLToPath(import.meta.url)), "..");
const NM = join(ROOT, "node_modules");
const read = p => readFileSync(join(NM, p));
const out = {};

// scripts
out["app/vendor/qrcode.min.js"] = read("qrcodejs/qrcode.min.js");
out["app/vendor/jsQR.min.js"] = Buffer.from("/*! jsQR 1.4.0 | Apache-2.0 | https://github.com/cozmo/jsQR */\n" +
  transformSync(read("jsqr/dist/jsQR.js").toString(), { minify: true, legalComments: "none", target: "es2017" }).code);
out["app/vendor/LICENSES.txt"] = Buffer.from(
  "Third-party code served by Fatin\n================================\n\n" +
  "qrcode.min.js — qrcodejs 1.0.0 (https://github.com/davidshimjs/qrcodejs)\n\n" + read("qrcodejs/LICENSE") +
  "\n\njsQR.min.js — jsQR 1.4.0 (https://github.com/cozmo/jsQR), minified from dist/jsQR.js\n\n" + read("jsqr/LICENSE"));

// fonts: the same families, weights and scripts the app used from Google Fonts
const FONTS = [["alexandria", "Alexandria", [400, 600, 800]], ["ibm-plex-sans-arabic", "IBM Plex Sans Arabic", [400, 500, 600]]];
const SUBSETS = ["arabic", "latin-ext", "latin"];
let css = "/* Self-hosted fonts (OFL-1.1, see OFL.txt). Generated by tools/vendor.mjs from @fontsource; do not edit. */\n";
for (const [pkg, family, weights] of FONTS) {
  for (const w of weights) for (const sub of SUBSETS) {
    const file = `${pkg}-${sub}-${w}-normal.woff2`;
    // the per-weight CSS lists every subset with its unicode-range; take the block for this subset
    const src = readFileSync(join(NM, "@fontsource", pkg, `${w}.css`), "utf8");
    const block = src.split("@font-face").find(b => b.includes(`/files/${file}`)) || "";
    const range = (block.match(/unicode-range:\s*([^;]+);/) || [])[1];
    if (!range) throw new Error("no unicode-range for " + file);
    out["app/fonts/" + file] = read(`@fontsource/${pkg}/files/${file}`);
    css += `@font-face{font-family:"${family}";font-style:normal;font-weight:${w};font-display:swap;src:url(${file}) format("woff2");unicode-range:${range.trim()}}\n`;
  }
}
out["app/fonts/fonts.css"] = Buffer.from(css);
out["app/fonts/OFL.txt"] = Buffer.concat(FONTS.map(([pkg, family]) => Buffer.concat([Buffer.from(`${family}\n${"=".repeat(family.length)}\n\n`), read(`@fontsource/${pkg}/LICENSE`), Buffer.from("\n\n")])));

if (process.argv.includes("--check")) {
  const bad = Object.entries(out).filter(([p, b]) => !existsSync(join(ROOT, p)) || !readFileSync(join(ROOT, p)).equals(b)).map(([p]) => p);
  const extra = ["app/vendor", "app/fonts"].flatMap(d => existsSync(join(ROOT, d)) ? readdirSync(join(ROOT, d)).map(f => d + "/" + f) : []).filter(p => !(p in out));
  if (bad.length || extra.length) { console.error("Vendored files differ from the pinned packages: " + [...bad, ...extra].join(", ")); process.exit(1); }
  console.log("vendored files match the pinned packages (" + Object.keys(out).length + " files)");
} else {
  for (const [p, b] of Object.entries(out)) { mkdirSync(dirname(join(ROOT, p)), { recursive: true }); writeFileSync(join(ROOT, p), b); }
  console.log("vendored " + Object.keys(out).length + " files");
}
